" ~/.vimrc


filetype off


call plug#begin('~/.vim/plugged')

source ~/.vim/config/plugins.vim

call plug#end()


filetype plugin indent on
syntax enable


source ~/.vim/config/settings.vim
source ~/.vim/config/ui.vim
source ~/.vim/config/keymaps.vim
source ~/.vim/config/nerdtree.vim
source ~/.vim/config/coc.vim
source ~/.vim/config/autocomplete.vim
source ~/.vim/config/functions.vim
